#!/usr/bin/env julia
# ---------------------------------------------------------------------------
# DIAGNOSTIC for R.O. Fox's hypothesis (2026-07-26): the nine odd fourth-order
# cross-moments dropped by the 26-moment reduction may matter in LOW-SPEED
# wall-bounded non-equilibrium flow (micro/nano channels), even though they
# cost nothing at high Mach.
#
# This script does NOT test the reduction. It answers the cheaper question that
# has to come first: in wall-bounded shear, are those moments even nonzero, and
# how big are they relative to what the reduction keeps? If they sit at roundoff,
# the hypothesis is dead here and no reduced solver needs writing. If they are
# comparable to the shear stress, the reduction test is worth the work.
#
# WHY COUETTE, AND WHICH THREE MOMENTS.
# The dropped set is the nine C_{ijk} with (i,j,k) a permutation of (3,1,0) or
# (2,1,1) -- exactly the fourth-order moments that are ODD IN TWO AXES. The kept
# six (400,040,004,220,202,022) are even in all three.
#
# In a planar normal shock (gradients in x, symmetric in y and z) every one of the
# nine vanishes IDENTICALLY by reflection symmetry. The Ma=2 shock comparison in
# ../roe-hyqmom-research therefore could not have seen them; it is not evidence
# either way.
#
# In planar Couette (u_x(y), wall normal y, homogeneous in z) the z -> -z symmetry
# kills six of the nine, leaving exactly three:
#
#     C310 = <Cx^3 Cy>,   C130 = <Cx Cy^3>,   C112 = <Cx Cy Cz^2>
#
# all odd-in-x and odd-in-y -- the SAME parity class as the shear stress
# C110 = <Cx Cy>. They are its fourth-order companions, nonzero for exactly the
# reason the shear stress is, and generated by the wall. That is the structural
# content of Fox's intuition and why wall-bounded shear discriminates where a
# shock cannot.
#
# PARAMETERIZATION. The sweep variable is the CHANNEL Knudsen number Kn_H =
# lambda_mu/H, the quantity the micro-flow literature reports. It is NOT the
# solver's tau-scaling parameter: with tau_ref = kn_tau/2 and Theta = 1,
#     lambda_mu = tau_ref*sqrt(Theta/2) = kn_tau/(2 sqrt 2).
# Sweeping kn_tau at fixed grid also silently destroys resolution -- cells per
# mean free path fall like kn_tau, so the near-continuum end buries the entire
# Knudsen layer inside one cell. Here the grid is refined with Kn_H to hold
# CELLS_PER_LAMBDA fixed, so every point is equally resolved.
#
# Env: PO_KNH, PO_CELLS_PER_LAMBDA, PO_UW, PO_ORDER, PO_TEND, PO_PR, PO_OMEGA
# ---------------------------------------------------------------------------
ENV["HYQMOM_SKIP_PLOTTING"] = "true"; ENV["CI"] = "true"
using Riemann35, MPI, Printf, LinearAlgebra, Statistics
using Riemann35: WALL_SPEC
MPI.Initialized() || MPI.Init()

const KNH   = [parse(Float64, s) for s in split(get(ENV, "PO_KNH", "1.0,0.5,0.2,0.1,0.05"), ",")]
const CPL   = parse(Float64, get(ENV, "PO_CELLS_PER_LAMBDA", "6.0"))
const NYMIN = parse(Int,     get(ENV, "PO_NYMIN", "24"))
const UW    = parse(Float64, get(ENV, "PO_UW", "0.1"))   # low speed: Ma ~ 0.1
const ORDER = parse(Int,     get(ENV, "PO_ORDER", "2"))
const TENDF = parse(Float64, get(ENV, "PO_TEND", "0.3"))
const MAXST = parse(Int,     get(ENV, "PO_MAXSTEPS", "400000"))
# Real-gas collision settings: ES-BGK at the monatomic Prandtl number and the argon
# VHS exponent. Pr = 1 (plain BGK) is the wrong gas for a wall problem, where the
# Knudsen layer transports heat as well as momentum.
const PR    = parse(Float64, get(ENV, "PO_PR", "0.6666666666666666"))
const OMEGA = parse(Float64, get(ENV, "PO_OMEGA", "0.81"))
const SIGP  = 1.1     # Maxwell slip coefficient, used ONLY to pick a good initial guess

"central moments C_{ijk} of one cell, as C[i+1,j+1,k+1]"
centrals(Mv::AbstractVector{Float64}) = M4toC4_3D(Mv...)

"""
    couette_field(KnH) -> (column, ny, nst, want, drift, kn_tau, cells_per_lambda)

Planar Couette at channel Knudsen number `KnH = lambda_mu/H`, with the grid refined
so that `lambda/dy = CPL`. Length unit is the channel height, `H = 1`, hence
`lambda = KnH` and `ny = CPL/KnH`.
"""
function couette_field(KnH::Float64; cpl = CPL, Uw = UW, order = ORDER, alpha = 1.0)
    halo = order == 3 ? 8 : 2
    H    = 1.0
    lam  = KnH*H
    ny   = max(NYMIN, round(Int, cpl/KnH))
    nx   = halo + 2; nz = 1
    dy   = H/ny; dx = dy; dz = dy
    decomp = setup_mpi_cartesian_3d(nx, ny, nz, halo, MPI.COMM_WORLD)
    rho0, T0 = 1.0, 1.0

    WALL_SPEC[] = (ylo = (Tw=T0, uw1=0.0, uw2=-Uw, alpha=alpha),
                   yhi = (Tw=T0, uw1=0.0, uw2=+Uw, alpha=alpha))
    BC = (xlo=:periodic, xhi=:periodic, ylo=:wall, yhi=:wall, zlo=:outflow, zhi=:outflow)

    # lambda_mu = tau_ref*sqrt(Theta/2) with Theta = 1  =>  tau_ref = lam*sqrt(2),
    # and the solver takes kn_tau = 2*tau_ref.
    tau_ref = lam*sqrt(2.0)
    kn_tau  = 2*tau_ref
    nu      = T0*tau_ref

    # Initial guess: the SLIP-corrected linear profile, not the no-slip one. The steady
    # state differs from it only by the Knudsen layer, so the transient is short. A
    # no-slip (or uniform) start makes the near-continuum cases cost ~1e6 steps, since
    # relaxing a global slope change takes a full diffusion time.
    A = Uw/(1 + 2*SIGP*KnH)
    M = zeros(nx+2halo, ny+2halo, nz, 35)
    for k in 1:nz, j in 1:(ny+2halo), i in 1:(nx+2halo)
        yj = ((j - halo) - 0.5)*dy
        ux = A*(2*clamp(yj/H, 0.0, 1.0) - 1.0)
        M[i,j,k,:] = InitializeM4_35(rho0, ux, 0.0, 0.0, T0,0,0, T0,0, T0)
    end

    dt   = 0.2*dy/(5.0*sqrt(T0))
    want = ceil(Int, (TENDF*H*H/nu)/dt)
    nst  = min(MAXST, want)

    dudy_of(Mf) = begin
        u = [Mf[halo+1, halo+j, 1, 2]/Mf[halo+1, halo+j, 1, 1] for j in 1:ny]
        lo = max(1, ny÷4); hi = min(ny, 3*ny÷4)
        (u[hi] - u[lo])/((hi-lo)*dy)
    end

    d_early = 0.0
    mark    = max(1, nst - nst÷10)
    for n in 1:nst
        step_highorder_3d!(M, dt, decomp, BC, nx, ny, nz, halo, dx, dy, dz, 0.0;
                           order = order, stage_bgk_kn = kn_tau, stage_bgk_exact = true,
                           Pr = PR, omega = OMEGA)
        n == mark && (d_early = dudy_of(M))
    end
    d_late = dudy_of(M)
    drift  = abs(d_late) > 0 ? abs(d_late - d_early)/abs(d_late) : NaN

    [M[halo+1, halo+j, 1, :] for j in 1:ny], ny, nst, want, drift, kn_tau, lam/dy
end

println("="^116)
println("ODD FOURTH-ORDER CROSS-MOMENTS IN WALL-BOUNDED SHEAR (diagnostic for the 26-moment reduction)")
@printf("planar Couette, H=1, Uw=%.2f (Ma~%.2f), order=%d, fully diffuse walls, ES-BGK Pr=%.3f omega=%.2f\n",
        UW, UW, ORDER, PR, OMEGA)
println("Sweep variable is the CHANNEL Knudsen number Kn_H = lambda_mu/H; grid refined to hold ~$(CPL) cells per lambda.")
println("S_ijk = C_ijk/(rho*Theta^2); shear stress s = C110/Theta. The three listed are the ONLY")
println("dropped moments that survive the z-symmetry of this flow. S220 is a KEPT moment; its")
println("EQUILIBRIUM value is 1, so compare its DEVIATION |S220-1|, not its value.")
println("="^116)
@printf("%6s %6s %7s %8s %11s %11s %11s %11s %11s %10s %8s\n",
        "Kn_H", "ny", "cell/lam", "where", "s=C110/Th", "S310", "S130", "S112",
        "|S220-1|", "max|Sodd|/|s|", "drift")
flush(stdout)
for KnH in KNH
    col, ny, nst, want, drift, kn_tau, cpl_act = couette_field(KnH)
    nst < want && @printf("# Kn_H=%.3f TRUNCATED at %d of %d steps -- UNCONVERGED\n", KnH, nst, want)
    for (tag, j) in (("wall", 1), ("centre", max(1, ny÷2)))
        Mv  = col[j]
        C   = centrals(Mv)
        Th  = (C[3,1,1] + C[1,3,1] + C[1,1,3])/3
        s   = C[2,2,1]/Th
        nrm = Th^2
        S310 = C[4,2,1]/nrm; S130 = C[2,4,1]/nrm; S112 = C[2,2,3]/nrm
        S220 = C[3,3,1]/nrm
        mx   = maximum(abs, (S310, S130, S112))
        @printf("%6.3f %6d %7.2f %8s %11.3e %11.3e %11.3e %11.3e %11.3e %10.3f %8.1e\n",
                KnH, ny, cpl_act, tag, s, S310, S130, S112, abs(S220 - 1),
                abs(s) > 0 ? mx/abs(s) : NaN, drift)
        flush(stdout)
    end
end
println("="^116)
println("READING THIS. The dropped three are DEVIATIONS from a Gaussian, so the scale to compare")
println("them against is the shear stress s and the deviation |S220-1| of the kept even moment --")
println("NOT S220 itself, which is ~1 for any near-Maxwellian state.")
println("  max|Sodd|/|s| >> 1 : the discarded moments carry more than the stress does. Fox is right")
println("                       and the reduction is a modelling choice with Knudsen-layer consequences.")
println("  max|Sodd|/|s| -> 0 as Kn_H -> 0 : they are a rarefaction effect that vanishes in the slip")
println("                       regime, so the reduction is safe for the micro-channel target after all.")
println("The TREND in Kn_H is the result here, not any single row.")
