"""
Golden test for the 3D HyQMOM 5th-order closure (`hyqmom_3D`).

Pins the Julia closure to reference values produced by the revised MATLAB
implementation (Code_Riemann_3D_35mom_july2026 `hyqmom_3D.m`, Appendix B), in
which the six mixed third-order closures S320, S230, S302, S203, S032, S023
were simplified (cross-coupling terms dropped). The reference values were
generated by running the MATLAB `hyqmom_3D.m` on 60 standardized-moment vectors
derived from particle-sampled realizable moment fields; inputs and outputs are
stored as plain text (no MAT/HDF5 dependency).

Regenerating: re-run both languages on identical inputs and overwrite
    test/goldenfiles/hyqmom_3D_golden_inputs.txt          (60 x 28)
    test/goldenfiles/hyqmom_3D_golden_outputs_matlab.txt  (60 x 21)
"""

using Test
using Riemann35
using DelimitedFiles

@testset "hyqmom_3D closure golden (MATLAB Appendix B)" begin
    gdir = joinpath(@__DIR__, "goldenfiles")
    inputs  = readdlm(joinpath(gdir, "hyqmom_3D_golden_inputs.txt"))
    expected = readdlm(joinpath(gdir, "hyqmom_3D_golden_outputs_matlab.txt"))

    @test size(inputs, 2) == 28
    @test size(expected, 2) == 21
    @test size(inputs, 1) == size(expected, 1)

    maxerr = 0.0
    for c in 1:size(inputs, 1)
        out = collect(hyqmom_3D(inputs[c, :]...))
        @test out ≈ expected[c, :] atol=1e-12 rtol=1e-10
        maxerr = max(maxerr, maximum(abs.(out .- expected[c, :])))
    end
    @info "hyqmom_3D golden: max |Δ| vs MATLAB = $maxerr over $(size(inputs,1)) cases"
    @test maxerr < 1e-12

    # Direct check of the six revised closures on a representative case,
    # guarding against accidental reversion to the full (old) expressions.
    let r = inputs[1, :]
        S300,S400,S110,S210,S310,S120,S220,S030,S130,S040,
        S101,S201,S301,S102,S202,S003,S103,S004,S011,S111,
        S211,S021,S121,S031,S012,S112,S013,S022 = r
        S320 = (S400 - (3*S300^2)/2)*S120 + ((3*S300)/2)*S220 - S300/2
        out = collect(hyqmom_3D(r...))
        @test out[3] ≈ S320 atol=1e-13   # index 3 == S320 in the return tuple
    end
end
