# Tests for the optional Wick/Grad degree-5 blend in `flux_closure_dev.jl`.
# 
# The collected expressions in `_wick5_central` were generated by summing over the 10 unordered
# index pairs and then gathering like terms by hand-off to a script. Gathered terms are exactly where
# a transcription error hides silently: a wrong coefficient still produces a plausible number, still
# has the right symmetry, and would show up only as a slightly worse closure. So the load-bearing
# test rebuilds every component from the definition, independently, and compares.

using Test, Riemann35
using Riemann35.FluxClosureDev: _wick5_central, WICK5_ALPHA, WICK5_GAIN

# ---------------------------------------------------------------------------------------------
# Reference implementation, written from the DEFINITION rather than from the collected form:
#   C_{ijklm} = sum over the 10 unordered pairs {ab} of C_{ab} * C_{(remaining three)}
# Deliberately slow and allocating -- it exists to disagree with the fast one if either is wrong.
function wick5_reference(C2::Dict, C3::Dict)
    out = Dict{NTuple{3,Int},Float64}()
    key(idxs) = (count(==(1), idxs), count(==(2), idxs), count(==(3), idxs))
    for combo in Iterators.product(1:3, 1:3, 1:3, 1:3, 1:3)
        idxs = collect(combo)
        issorted(idxs) || continue                     # each multiset once
        acc = 0.0
        for a in 1:4, b in (a+1):5
            rest = [idxs[t] for t in 1:5 if t != a && t != b]
            acc += C2[key([idxs[a], idxs[b]])] * C3[key(rest)]
        end
        out[key(idxs)] = acc
    end
    out
end

@testset "Wick degree-5 closure" begin
    rng_vals = [0.7213, -0.1187, 0.3391, 1.4432, 0.0913, 0.8821,      # C2: 200,110,101,020,011,002
                -0.2314, 0.5527, -0.7719, 0.1103, 0.9014, -0.4428,    # C3: 300,210,201,120,111,102
                0.6612, -0.3305, 0.2218, -0.8836]                     # C3: 030,021,012,003
    C200,C110,C101,C020,C011,C002,
    C300,C210,C201,C120,C111,C102,C030,C021,C012,C003 = rng_vals

    C2 = Dict((2,0,0)=>C200, (1,1,0)=>C110, (1,0,1)=>C101,
              (0,2,0)=>C020, (0,1,1)=>C011, (0,0,2)=>C002)
    C3 = Dict((3,0,0)=>C300, (2,1,0)=>C210, (2,0,1)=>C201, (1,2,0)=>C120, (1,1,1)=>C111,
              (1,0,2)=>C102, (0,3,0)=>C030, (0,2,1)=>C021, (0,1,2)=>C012, (0,0,3)=>C003)

    fast = _wick5_central(C200,C110,C101,C020,C011,C002,
                          C300,C210,C201,C120,C111,C102,C030,C021,C012,C003)
    ref = wick5_reference(C2, C3)
    order = [(5,0,0),(4,1,0),(4,0,1),(3,2,0),(3,1,1),(3,0,2),(2,3,0),(2,2,1),(2,1,2),(2,0,3),
             (1,4,0),(1,3,1),(1,2,2),(1,1,3),(1,0,4),(0,5,0),(0,4,1),(0,3,2),(0,2,3),(0,1,4),(0,0,5)]

    @testset "every component matches the definition" begin
        @test length(fast) == 21
        for (k, key) in enumerate(order)
            @test fast[k] ≈ ref[key] rtol=1e-14
        end
    end

    # A Gaussian has vanishing odd central moments, so C3 = 0 and the Wick sum -- every term of
    # which carries exactly one C3 factor -- must vanish identically. The true degree-5 moments of
    # a Gaussian are also zero, so the closure is EXACT there. If this fails, some term has been
    # written with two C2 factors and no C3, which the component test above could still pass if the
    # reference carried the same mistake.
    @testset "exact for a Gaussian (C3 = 0)" begin
        z = _wick5_central(C200,C110,C101,C020,C011,C002,
                           0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
        @test all(==(0.0), z)
    end

    # Scaling: C2 ~ v^2 and C3 ~ v^3, so every term is v^5 and the whole thing must scale as v^5
    # under a uniform velocity rescaling. This catches a term built from the wrong moment degree.
    @testset "scales as velocity^5" begin
        s = 1.7
        got = _wick5_central(s^2*C200,s^2*C110,s^2*C101,s^2*C020,s^2*C011,s^2*C002,
                             s^3*C300,s^3*C210,s^3*C201,s^3*C120,s^3*C111,s^3*C102,
                             s^3*C030,s^3*C021,s^3*C012,s^3*C003)
        for k in 1:21
            @test got[k] ≈ s^5 * fast[k] rtol=1e-12
        end
    end

    # THE DEFAULT MUST BE OFF. This file is the single source for the CPU and GPU flux, so a
    # non-zero default would move every pinned number in the project at once, silently.
    @testset "blend is off by default" begin
        @test WICK5_ALPHA == 0.0
        @test 0.9 < WICK5_GAIN < 1.0     # the a-priori fit; guards a typo'd override
    end
end
