"""
    C4toM4_3D(M000, umean, vmean, wmean, C200, C110, C101, C020, C011, C002,
              C300, C210, C201, C120, C111, C102, C030, C021, C012, C003,
              C400, C310, C301, C220, C211, C202, C130, C121, C112, C103, C040, C031, C022, C013, C004)

Convert central moments to raw moments (autogenerated from Symbolic Math Toolbox).
Returns 5x5x5 array of raw moments.
"""
function C4toM4_3D(M000, umean, vmean, wmean, C200, C110, C101, C020, C011, C002,
                   C300, C210, C201, C120, C111, C102, C030, C021, C012, C003,
                   C400, C310, C301, C220, C211, C202, C130, C121, C112, C103, C040, C031, C022, C013, C004)
    @fastmath begin
        t2 = umean^2
        t3 = umean^3
        t4 = vmean^2
        t5 = vmean^3
        t6 = wmean^2
        t7 = wmean^3
        
        # Construct 5x5x5 array (125 elements total)
        # This is a direct translation of the MATLAB autogenerated code
        M4 = reshape([
            M000, M000*umean, M000*t2+C200*M000, M000*t3+C300*M000+C200*M000*umean*3.0,
            M000*t2^2+C400*M000+C200*M000*t2*6.0+C300*M000*umean*4.0,
            M000*vmean, C110*M000+M000*umean*vmean,
            C210*M000+C110*M000*umean*2.0+C200*M000*vmean+M000*t2*vmean,
            C310*M000+C110*M000*t2*3.0+C210*M000*umean*3.0+C300*M000*vmean+M000*t3*vmean+C200*M000*umean*vmean*3.0,
            0.0, M000*t4+C020*M000,
            C120*M000+C020*M000*umean+C110*M000*vmean*2.0+M000*t4*umean,
            C220*M000+C020*M000*t2+C200*M000*t4+C120*M000*umean*2.0+C210*M000*vmean*2.0+M000*t2*t4+C110*M000*umean*vmean*4.0,
            0.0, 0.0, M000*t5+C030*M000+C020*M000*vmean*3.0,
            C130*M000+C110*M000*t4*3.0+C030*M000*umean+C120*M000*vmean*3.0+M000*t5*umean+C020*M000*umean*vmean*3.0,
            0.0, 0.0, 0.0, M000*t4^2+C040*M000+C020*M000*t4*6.0+C030*M000*vmean*4.0,
            0.0, 0.0, 0.0, 0.0, M000*wmean, C101*M000+M000*umean*wmean,
            C201*M000+C101*M000*umean*2.0+C200*M000*wmean+M000*t2*wmean,
            C301*M000+C101*M000*t2*3.0+C201*M000*umean*3.0+C300*M000*wmean+M000*t3*wmean+C200*M000*umean*wmean*3.0,
            0.0, C011*M000+M000*vmean*wmean,
            C111*M000+C011*M000*umean+C101*M000*vmean+C110*M000*wmean+M000*umean*vmean*wmean,
            C211*M000+C011*M000*t2+C111*M000*umean*2.0+C201*M000*vmean+C210*M000*wmean+M000*t2*vmean*wmean+C101*M000*umean*vmean*2.0+C110*M000*umean*wmean*2.0+C200*M000*vmean*wmean,
            0.0, 0.0, C021*M000+C011*M000*vmean*2.0+C020*M000*wmean+M000*t4*wmean,
            C121*M000+C101*M000*t4+C021*M000*umean+C111*M000*vmean*2.0+C120*M000*wmean+M000*t4*umean*wmean+C011*M000*umean*vmean*2.0+C020*M000*umean*wmean+C110*M000*vmean*wmean*2.0,
            0.0, 0.0, 0.0,
            C031*M000+C011*M000*t4*3.0+C021*M000*vmean*3.0+C030*M000*wmean+M000*t5*wmean+C020*M000*vmean*wmean*3.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, M000*t6+C002*M000,
            C102*M000+C002*M000*umean+C101*M000*wmean*2.0+M000*t6*umean,
            C202*M000+C002*M000*t2+C200*M000*t6+C102*M000*umean*2.0+C201*M000*wmean*2.0+M000*t2*t6+C101*M000*umean*wmean*4.0,
            0.0, 0.0, C012*M000+C002*M000*vmean+C011*M000*wmean*2.0+M000*t6*vmean,
            C112*M000+C110*M000*t6+C012*M000*umean+C102*M000*vmean+C111*M000*wmean*2.0+M000*t6*umean*vmean+C002*M000*umean*vmean+C011*M000*umean*wmean*2.0+C101*M000*vmean*wmean*2.0,
            0.0, 0.0, 0.0,
            C022*M000+C002*M000*t4+C020*M000*t6+C012*M000*vmean*2.0+C021*M000*wmean*2.0+M000*t4*t6+C011*M000*vmean*wmean*4.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            M000*t7+C003*M000+C002*M000*wmean*3.0,
            C103*M000+C101*M000*t6*3.0+C003*M000*umean+C102*M000*wmean*3.0+M000*t7*umean+C002*M000*umean*wmean*3.0,
            0.0, 0.0, 0.0,
            C013*M000+C011*M000*t6*3.0+C003*M000*vmean+C012*M000*wmean*3.0+M000*t7*vmean+C002*M000*vmean*wmean*3.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
            M000*t6^2+C004*M000+C002*M000*t6*6.0+C003*M000*wmean*4.0,
            0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
        ], 5, 5, 5)
        
        return M4
    end
end
