"""
    lower_bound_S220(S011, S012, S021, S101, S102, S110, S111, S120, S201, S210)

Compute lower bound for S220 moment based on standardized moments.

This function was autogenerated by MATLAB Symbolic Math Toolbox.

# Arguments
- 10 standardized moment components

# Returns
- 3-element vector of S220 bounds
"""
@fastmath function lower_bound_S220(S011,S012,S021,S101,S102,S110,S111,S120,S201,S210)
    t2 = S011^2
    t3 = S012^2
    t4 = S021^2
    t5 = S101^2
    t6 = S102^2
    t7 = S110^2
    t8 = S111^2
    t9 = S120^2
    t10 = S201^2
    t11 = S210^2
    t12 = S011*S101*S110*2.0
    t13 = -t8
    t14 = -t12
    t15 = t2*t5
    t16 = t2*t7
    t17 = t5*t7
    t18 = t2+t5+t7+t14-1.0
    t19 = 1.0/t18
    mt1 = [t19*(-t7-t9-t11+t13+t16+t17+t2*t11+t5*t9+t7*t8+t7^2+S011*S111*S120*2.0+S101*S111*S210*2.0+S110*S120*S210*2.0-S011*S101*S110^3*2.0-S011*S101*S120*S210*2.0-S011*S110*S111*S210*2.0-S101*S110*S111*S120*2.0),t19*(-t5-t6-t10+t13+t15+t17+t2*t10+t5*t8+t6*t7+t5^2+S011*S102*S111*2.0+S101*S102*S201*2.0+S110*S111*S201*2.0-S011*S101^3*S110*2.0-S011*S101*S111*S201*2.0-S011*S102*S110*S201*2.0-S101*S102*S110*S111*2.0)]
    mt2 = [t19*(-t2-t3-t4+t13+t15+t16+t4*t5+t2*t8+t3*t7+t2^2+S011*S012*S021*2.0+S012*S101*S111*2.0+S021*S110*S111*2.0-S011^3*S101*S110*2.0-S011*S012*S110*S111*2.0-S011*S021*S101*S111*2.0-S012*S021*S101*S110*2.0)]
    S22 = [mt1...,mt2...]
    return S22
end
