"""
    Moments5_3D(M4)

Compute 3D HyQMOM closure for fluxes.

Computes 5th-order closure moments from 4th-order moments using the HyQMOM method.

# Arguments
- `M4`: 35-element vector of 4th-order raw moments

# Returns
- `M5`: 21-element vector of 5th-order raw moments
- `C5`: 21-element vector of 5th-order central moments
- `S5`: 21-element vector of 5th-order standardized moments
"""
function Moments5_3D(M4)
    # Extract moments
    M000 = M4[1]
    M100 = M4[2]; M200 = M4[3]; M300 = M4[4]; M400 = M4[5]
    M010 = M4[6]; M110 = M4[7]; M210 = M4[8]; M310 = M4[9]
    M020 = M4[10]; M120 = M4[11]; M220 = M4[12]
    M030 = M4[13]; M130 = M4[14]
    M040 = M4[15]
    M001 = M4[16]; M101 = M4[17]; M201 = M4[18]; M301 = M4[19]
    M002 = M4[20]; M102 = M4[21]; M202 = M4[22]
    M003 = M4[23]; M103 = M4[24]
    M004 = M4[25]
    M011 = M4[26]; M111 = M4[27]; M211 = M4[28]
    M021 = M4[29]; M121 = M4[30]
    M031 = M4[31]
    M012 = M4[32]; M112 = M4[33]
    M013 = M4[34]
    M022 = M4[35]
    
    # Convert to central and standardized moments
    C4, S4 = M2CS4_35(M4)
    
    # Extract standardized moments (same indexing as M4)
    S300 = S4[4]; S400 = S4[5]
    S110 = S4[7]; S210 = S4[8]; S310 = S4[9]
    S120 = S4[11]; S220 = S4[12]
    S030 = S4[13]; S130 = S4[14]
    S040 = S4[15]
    S101 = S4[17]; S201 = S4[18]; S301 = S4[19]
    S102 = S4[21]; S202 = S4[22]
    S103 = S4[24]
    S003 = S4[23]; S004 = S4[25]
    S011 = S4[26]; S111 = S4[27]; S211 = S4[28]
    S021 = S4[29]; S121 = S4[30]
    S031 = S4[31]
    S012 = S4[32]; S112 = S4[33]
    S013 = S4[34]
    S022 = S4[35]
    
    # Compute 5th-order standardized moments using Riemann35 closure
    S500, S410, S320, S230, S140, S401, S302, S203, S104, S311, S221, S131,
    S212, S113, S122, S050, S041, S032, S023, S014, S005 = 
        hyqmom_3D(S300, S400, S110, S210, S310, S120, S220, S030, S130, S040,
                  S101, S201, S301, S102, S202, S003, S103, S004, S011, S111,
                  S211, S021, S121, S031, S012, S112, S013, S022)
    
    # Extract variances for conversion
    C200 = C4[3]; C020 = C4[10]; C002 = C4[20]
    sC200 = sqrt(max(C200, eps()))
    sC020 = sqrt(max(C020, eps()))
    sC002 = sqrt(max(C002, eps()))
    
    # Convert standardized to central moments (C = S * sigma^order)
    C500 = S500 * sC200^5
    C410 = S410 * sC200^4 * sC020
    C320 = S320 * sC200^3 * sC020^2
    C230 = S230 * sC200^2 * sC020^3
    C140 = S140 * sC200 * sC020^4
    C401 = S401 * sC200^4 * sC002
    C302 = S302 * sC200^3 * sC002^2
    C203 = S203 * sC200^2 * sC002^3
    C104 = S104 * sC200 * sC002^4
    C311 = S311 * sC200^3 * sC020 * sC002
    C221 = S221 * sC200^2 * sC020^2 * sC002
    C131 = S131 * sC200 * sC020^3 * sC002
    C212 = S212 * sC200^2 * sC020 * sC002^2
    C113 = S113 * sC200 * sC020 * sC002^3
    C122 = S122 * sC200 * sC020^2 * sC002^2
    C050 = S050 * sC020^5
    C041 = S041 * sC020^4 * sC002
    C032 = S032 * sC020^3 * sC002^2
    C023 = S023 * sC020^2 * sC002^3
    C014 = S014 * sC020 * sC002^4
    C005 = S005 * sC002^5
    
    # Convert central to raw moments
    umean = M100 / M000
    vmean = M010 / M000
    wmean = M001 / M000
    
    # Extract all 4th-order central moments needed for C5toM5_3D
    C110 = C4[7]; C101 = C4[17]; C011 = C4[26]
    C300 = C4[4]; C210 = C4[8]; C201 = C4[18]
    C120 = C4[11]; C111 = C4[27]; C102 = C4[21]
    C030 = C4[13]; C021 = C4[29]; C012 = C4[32]
    C003 = C4[23]
    C400 = C4[5]; C310 = C4[9]; C301 = C4[19]
    C220 = C4[12]; C211 = C4[28]; C202 = C4[22]
    C130 = C4[14]; C121 = C4[30]; C112 = C4[33]; C103 = C4[24]
    C040 = C4[15]; C031 = C4[31]; C022 = C4[35]; C013 = C4[34]; C004 = C4[25]
    
    # Use autogenerated C5toM5_3D function
    M5_full = C5toM5_3D(M000, umean, vmean, wmean,
                        C200, C110, C101, C020, C011, C002,
                        C300, C210, C201, C120, C111, C102, C030, C021, C012, C003,
                        C400, C310, C301, C220, C211, C202, C130, C121, C112, C103,
                        C040, C031, C022, C013, C004,
                        C500, C410, C320, C230, C140, C401, C302, C203, C104,
                        C311, C221, C131, C212, C113, C122,
                        C050, C041, C032, C023, C014, C005)
    
    # Extract 5th-order moments (indices for 5th order in 6x6x6 array)
    # M500, M410, M320, M230, M140, M401, M302, M203, M104, M311, M221, M131,
    # M212, M113, M122, M050, M041, M032, M023, M014, M005
    M500 = M5_full[6,1,1]
    M410 = M5_full[5,2,1]; M320 = M5_full[4,3,1]; M230 = M5_full[3,4,1]; M140 = M5_full[2,5,1]
    M401 = M5_full[5,1,2]; M302 = M5_full[4,1,3]; M203 = M5_full[3,1,4]; M104 = M5_full[2,1,5]
    M311 = M5_full[4,2,2]; M221 = M5_full[3,3,2]; M131 = M5_full[2,4,2]
    M212 = M5_full[3,2,3]; M113 = M5_full[2,2,4]; M122 = M5_full[2,3,3]
    M050 = M5_full[1,6,1]; M041 = M5_full[1,5,2]; M032 = M5_full[1,4,3]
    M023 = M5_full[1,3,4]; M014 = M5_full[1,2,5]; M005 = M5_full[1,1,6]
    
    M5 = [M500; M410; M320; M230; M140; M401; M302; M203; M104; M311; M221; M131;
          M212; M113; M122; M050; M041; M032; M023; M014; M005]
    
    C5 = [C500; C410; C320; C230; C140; C401; C302; C203; C104; C311; C221; C131;
          C212; C113; C122; C050; C041; C032; C023; C014; C005]
    
    S5 = [S500; S410; S320; S230; S140; S401; S302; S203; S104; S311; S221; S131;
          S212; S113; S122; S050; S041; S032; S023; S014; S005]
    
    return M5, C5, S5
end
